### ISSUE TITLE
spotify-latest@1.1.35.458.g891674f3: hash check failed

### ISSUE THREAD

**Issue by Tsubajashi** [TheRandomLabs/Scoop-Spotify#11]
Updating 'spotify-latest' (1.1.34.694.gac68a2b3 -> 1.1.35.458.g891674f3)
Downloading new version
SpotifyFullSetup.exe (76.8 MB) [==============================================================================] 100%
Checking hash of SpotifyFullSetup.exe ... ERROR Hash check failed!
App:         spotify/spotify-latest
URL:         https://download.scdn.co/SpotifyFullSetup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    7694b896b1e2984a4ab53ded1c8762f45786357dd46192a507dbd53534fb4789
Actual:      f752d89788d1e82b03ae536d9191c0fff69fcb85cd103a56818adf9b9f35b982

if there is more stuff needed to be helpful, i gladly try to provide everything.

**Comment by TheRandomLabs** [comment]
Fixed!
