### ISSUE TITLE
spotify-latest@1.1.37.690.g8f3b16fc: hash check failed

### ISSUE THREAD

**Issue by StavZ** [TheRandomLabs/Scoop-Spotify#15]
Checking hash of SpotifyFullSetup.exe ... ERROR Hash check failed!
App:         spotify/spotify-latest
URL:         https://download.scdn.co/SpotifyFullSetup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d96fd7c3f3970fbb26192b2d8022efdd2edc7fb60669f2bb1d351ad3e816c8f5
Actual:      ee2957008b72e044738bcbd4816fe32698ee361b9462556bad5354768707873a

**Comment by TheRandomLabs** [comment]
Fixed, thank you!
