### ISSUE TITLE
spotify-latest@1.1.38.558.g4b100958: hash check failed

### ISSUE THREAD

**Issue by ShunranSasaki** [TheRandomLabs/Scoop-Spotify#19]
> scoop install spotify-latest
Installing 'spotify-latest' (1.1.38.558.g4b100958) [64bit]
SpotifyFullSetup.exe (77.4 MB) [==============================================================================] 100%
Checking hash of SpotifyFullSetup.exe ... ERROR Hash check failed!
App:         spotify/spotify-latest
URL:         https://download.scdn.co/SpotifyFullSetup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    ee2957008b72e044738bcbd4816fe32698ee361b9462556bad5354768707873a
Actual:      752f3b4b5e41cc7948ed8050099bdca1bb109a3b64d81292b1da3486a5a55e59

**Comment by TheRandomLabs** [comment]
Fixed!
