### ISSUE TITLE
Manifest version has unsupported character '<'.

### ISSUE THREAD

**Issue by Algo-ryth-mix** [TheRandomLabs/Scoop-Spotify#21]
running:
` scoop install spotify-latest -k` yields
`Manifest version has unsupported character '<'.`
Previous version `1.1.39.612.g1e7e78a4` works just fine so I believe that 
https://github.com/TheRandomLabs/Scoop-Spotify/commit/9e6b62c2286a868ce166b6890b49e39f90dcba32 is probably the issue

**Comment by TheRandomLabs** [comment]
Whoops, my bad.
