### ISSUE TITLE
spotify-latest@1.1.39.612.g1e7e78a4: hash check failed

### ISSUE THREAD

**Issue by benfishbus** [TheRandomLabs/Scoop-Spotify#22]
Updating 'spotify-latest' (1.1.38.558.g4b100958 -> 1.1.39.612.g1e7e78a4)
Downloading new version
SpotifyFullSetup.exe (78.3 MB) [==============================================================================] 100%
Checking hash of SpotifyFullSetup.exe ... ERROR Hash check failed!
App:         spotify/spotify-latest
URL:         https://download.scdn.co/SpotifyFullSetup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    752f3b4b5e41cc7948ed8050099bdca1bb109a3b64d81292b1da3486a5a55e59
Actual:      8067c8dafde4ce9f065fa1079f2cee14ad97dab62f3901fb5569286371c88879

**Comment by TheRandomLabs** [comment]
Fixed.
