### ISSUE TITLE
spotify-latest@1.1.40.508.gd5bc2931: hash check failed

### ISSUE THREAD

**Issue by Tsubajashi** [TheRandomLabs/Scoop-Spotify#24]
i guess im back!

Updating 'spotify-latest' (1.1.39.612.g1e7e78a4 -> 1.1.40.508.gd5bc2931)
Downloading new version
SpotifyFullSetup.exe (77.4 MB) [==============================================================================] 100%
Checking hash of SpotifyFullSetup.exe ... ERROR Hash check failed!
App:         spotify/spotify-latest
URL:         https://download.scdn.co/SpotifyFullSetup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    8067c8dafde4ce9f065fa1079f2cee14ad97dab62f3901fb5569286371c88879
Actual:      752f3b4b5e41cc7948ed8050099bdca1bb109a3b64d81292b1da3486a5a55e59

**Comment by Tsubajashi** [comment]
Excuse me? im quite sure that i didnt do anything wrong.

**Comment by Tsubajashi** [comment]
i see :)

**Comment by TheRandomLabs** [comment]
My bad, it was `-s`. I'll add this to the README. :)
