### ISSUE TITLE
spotify-latest@1.1.41.634.gc2c73ca7: hash check failed

### ISSUE THREAD

**Issue by lemonbigbig** [TheRandomLabs/Scoop-Spotify#25]
Checking hash of SpotifyFullSetup.exe ... ERROR Hash check failed!
App:         spotify/spotify-latest
URL:         https://download.scdn.co/SpotifyFullSetup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    715a05026ee1dd6771f2b9d708bdfc25390fab1d139f9b6a660a37f63cba07a4
Actual:      8067c8dafde4ce9f065fa1079f2cee14ad97dab62f3901fb5569286371c88879

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/TheRandomLabs/Scoop-Spotify/issues/new?title=spotify-latest%401.1.41.634.gc2c73ca7%3a+hash+check+failed

**Comment by TheRandomLabs** [comment]
Please read the README. :)
