### ISSUE TITLE
spotify-latest@1.1.41.634.gc2c73ca7: hash check failed

### ISSUE THREAD

**Issue by bricle** [TheRandomLabs/Scoop-Spotify#27]
Download: Status Legend:
Download: (OK):download completed.
Checking hash of SpotifyFullSetup.exe ... ERROR Hash check failed!
App:         spotify/spotify-latest
URL:         https://download.scdn.co/SpotifyFullSetup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    715a05026ee1dd6771f2b9d708bdfc25390fab1d139f9b6a660a37f63cba07a4
Actual:      8067c8dafde4ce9f065fa1079f2cee14ad97dab62f3901fb5569286371c88879

**Comment by bricle** [comment]
Sorry now i read the readme
sorry for disturbing

**Comment by TheRandomLabs** [comment]
All good.
