### ISSUE TITLE
spotify-latest@1.1.44.538.g8057de92: hash check failed

### ISSUE THREAD

**Issue by g4cm4n** [TheRandomLabs/Scoop-Spotify#28]
Checking hash of SpotifyFullSetup.exe ... ERROR Hash check failed!
App:         spotify/spotify-latest
URL:         https://download.scdn.co/SpotifyFullSetup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    8593986e6ca2807846644dbd0687663cb4d1f4620356ed4b19feec32bfa9fda0
Actual:      d3665523ce60989f35c8cd0fea72e9a2bd07e2ba064ae2a316c55ca7b7d76a11

**Comment by TheRandomLabs** [comment]
Refer to the README.
