### ISSUE TITLE
Hash check for spotify-latest fails, github-actions bot cannot reproduce

### ISSUE THREAD

**Issue by RaphaelTarita** [TheRandomLabs/Scoop-Spotify#30]
I previously opened #23, but the github-actions bot was unable to reproduce the hash check failure and therefore closed the issue. But I couldn't fix it, the issue persists. I tried:

```
scoop cache rm *
scoop cleanup *
scoop uninstall spotify-latest
scoop install spotify-latest
```
But I get the same error, still. Even after restarting my machine and retrying the above commands, I still get the wrong hash:

Expected: `5bd3ceba2a2e4769c3765d42e01ce87a22ce8cdeb908cd315e80ee7b92d8f57f`
Actual: `8593986e6ca2807846644dbd0687663cb4d1f4620356ed4b19feec32bfa9fda0`

I don't know why the bot was unable to reproduce the issue, but it still remains. Please fix it.

**Comment by TheRandomLabs** [comment]
https://github.com/TheRandomLabs/Scoop-Spotify#spotify-latest-hash-check-failed
