### ISSUE TITLE
Hash check failed

### ISSUE THREAD

**Issue by sebastianks** [TheRandomLabs/Scoop-Spotify#33]
Hello,

I tried to install spotify-latest, but I get the hash check failed error. When I run `scoop update -s spotify-latest` as you state in the README, but then I have to run the spotify installer my self from scoop\apps\spotify-latest, and I don't think that is how it should be?

The error log:
```
Installing 'spotify-latest' (1.1.48.625.g1c87c7f7) [64bit]
SpotifyFullSetup.exe (81.8 MB) [==============================================================================] 100%
Checking hash of SpotifyFullSetup.exe ... ERROR Hash check failed!
App:         spotify/spotify-latest
URL:         https://download.scdn.co/SpotifyFullSetup.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    9eecab4a43a6c4de66643a84977eb29f95d450ac068f2e0bd77e49f3970ed898
Actual:      02b3f3bdc7a1bd6dec822a73c8d12d5cdfa9ed76385c6fd33148d786801c90d4
```

**Comment by TheRandomLabs** [comment]
Can you show me the console output when you use `-s`?

**Comment by sebastianks** [comment]
```
spotify-latest: 1.1.48.625.g1c87c7f7 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
volcano master = $ scoop status
Scoop is up to date.
These app manifests have been removed:
    spotify-latest
These apps failed to install:
    spotify-latest
```

**Comment by TheRandomLabs** [comment]
All good. I meant when it was actually being updated. Can you try `scoop uninstall spotify-latest` and then `scoop install -s spotify-latest`? Send me the console output.

**Comment by sebastianks** [comment]
Ah, sorry. I was confused by the README saying "To work around this issue, pass the `-s` or `--skip` flag to Scoop when updating the package.". So I thought I should install and then do: `scoop update -s spotify-install`. All looks good now, when using `scoop install -s spotify-latest`

**Comment by TheRandomLabs** [comment]
Ah, sick. 😄
