### ISSUE TITLE
spicetify-jqbx support

### ISSUE THREAD

**Issue by camjac251** [TheRandomLabs/Scoop-Spotify#4]
Are spicetify extensions supported by this repository? Would it be possible to add support for https://github.com/Kasama/spicetify-jqbx

**Comment by TheRandomLabs** [comment]
Yep, done!

**Comment by camjac251** [comment]
oh wow that was fast. thank you

**Comment by TheRandomLabs** [comment]
I already had a manifest for `genius-spicetify`, so it didn't take very long. :)
