### ISSUE TITLE
Prefs is not created when using scoop to install spotify

### ISSUE THREAD

**Issue by AbhayAysola** [TheRandomLabs/Scoop-Spotify#9]
I used scoop to install spotify and when I try to use ``spicetify backup``
Its gives me this error

``error C:\Users\user\scoop\apps\spotify-latest\current\prefs does not exist or is not a valid path. Please manually set "prefs_path" in config.ini to correct path of "prefs" file.``

I tried searching for the prefs file in ``:\Users\user\scoop`` but it wasn't there.

**Comment by TheRandomLabs** [comment]
`prefs_path` should be left as `%APPDATA%\Roaming\Spotify\prefs` in the Spicetify configuration.
